services:
  web:
    build: .
    ports:
      - "8000:80"     # Mapping host port:8000 to container port:80
    volumes:
      - .:/app
      - /app/.venv
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia  # TODO: Couldn't test on a CUDA machine yet..
    #           count: 1
    #           capabilities: [gpu]
  
  mongodb:
    image: mongodb/mongodb-community-server:8.0.4-ubi9
    ports:
      - "27017:27017"
    # volumes:    # TODO: Still ends with a bug. App does not find DB after restart. Fix!
    #   - type: bind
    #     source: ./database/data
    #     target: /data/db