[project]
name = "ChemNetwork"
version = "0.0.1"
description = "Network for prediction of chemical properties"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]",
    "httpx2",
    "pydantic-settings",
    "pytest",
    "sqlmodel",
    "uvicorn",
    "numpy",
    "polars",
    "hydra-core",
    "tqdm",
    "wandb",
    "torch",
    "torchvision",
    "scikit-learn",
    "scipy",
    "matplotlib",
    "httpx2>=2.12.0",
]
[tool.fastapi]
entrypoint = "app.main:app"

[tool.pytest.ini_options]
pythonpath = ["."]
