defaults:
  - model: mlp
  - train_parameters: flow_matching_parameters
  - data: flow_matching_data_param

wandb:
  project: "chemnetwork-flow-matching"
  entity: null
  mode: "online"

hydra:
  run:
    dir: runs/${now:%Y-%m-%d_%H-%M-%S}-${train_parameters.comment}
  sweep:
    dir: runs/${now:%Y-%m-%d_%H-%M-%S}-${train_parameters.comment}